#!/bin/bash
for s in 0 1 2 3; do
  for i in 0 1 2 3 4 5 6 7; do
    let cpu=$s*8+$i
    v=`cat /sys/devices/system/cpu/cpu$cpu/online`
    echo -n -e "CPU$cpu $v\t"
  done
  echo
done
#!/bin/bash
#for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31; 
#do
#  echo "CPU$i: "
#  cat /sys/devices/system/cpu/cpu$i/online
#done
